- name: open ssh server install
  apt:
    name: openssh-server
    update_cache: yes
    cache_valid_time: 3600
  tags: ssh

# sshd
- name: sshd is configured
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644
  tags: ssh

- stat:
    path: /etc/ssh/ssh_host_rsa_key
  register: ssh_host_rsa_key
- stat:
    path: /etc/ssh/ssh_host_ecdsa_key
  register: ssh_host_ecdsa_key
- stat:
    path: /etc/ssh/ssh_host_ed25519_key
  register: ssh_host_ed25519_key

- name: ssh keys generate
  shell: "bash -lc 'ssh-keygen -A'"
  check_mode: no
  changed_when: false
  when:
    - not ssh_host_rsa_key.stat.exists or not ssh_host_ecdsa_key.stat.exists or not ssh_host_ed25519_key.stat.exists
